langs:
  - english
  - français
  - español
  - deutsch

countries:
  - United States
  - France
  - United Kingdom
  - Russia

decks:
  types:
    - Lesson
    - Flashcard
    - Questionnaire
  levels:
    - Start
    - Medium
    - Complex
    - Expert

  subjects:
    - English
    - Mathematics
    - Statistics
    - Physics